version: "3.8"

services:
  # BDD PostgreSQL
  postgres:
    image: postgres:16
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Backend Expresss
  backend:
    build:
      context: ./backend
    container_name: ecommerce-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ecommerce-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
    container_name: ecommerce-web
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
